package com.github.no_name_provided.fun_fluids.datagen.providers;

import com.github.no_name_provided.fun_fluids.client.registries.ParticleRegistry;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.Identifier;
import net.neoforged.neoforge.client.data.ParticleDescriptionProvider;

/**
 * This is where we create our particle description files. They define the (progression) of textures files used by
 * particles.
 */
public class FFParticleDescriptionProvider extends ParticleDescriptionProvider {
    /**
     * Creates an instance of the data provider.
     *
     * @param output the expected root directory the data generator outputs to
     */
    public FFParticleDescriptionProvider(PackOutput output) {
        super(output);
    }
    
    /**
     * Registers the particle descriptions generated by {@link //#sprite(ParticleType, Identifier)} or one of the
     * {@link #spriteSet(ParticleType, Iterable) sprite set methods}.
     *
     * <p>This particular particle could be registered more efficiently with the overload that takes
     * an integer, but I wanted to leave my options open.</p>
     */
    @Override protected void addDescriptions() {
        spriteSet(
                ParticleRegistry.MIST_PARTICLE.get(),
                Identifier.withDefaultNamespace("generic_7"),
                Identifier.withDefaultNamespace("generic_6"),
                Identifier.withDefaultNamespace("generic_5"),
                Identifier.withDefaultNamespace("generic_4"),
                Identifier.withDefaultNamespace("generic_3"),
                Identifier.withDefaultNamespace("generic_2"),
                Identifier.withDefaultNamespace("generic_1"),
                Identifier.withDefaultNamespace("generic_0")
        );
    }
}
