package com.github.no_name_provided.fun_fluids.datagen.providers;

import com.github.no_name_provided.fun_fluids.client.registries.ParticleRegistry;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.neoforged.neoforge.common.data.ParticleDescriptionProvider;

public class FFParticleDescriptionProvider extends ParticleDescriptionProvider {
    /**
     * Creates an instance of the data provider.
     *
     * @param output     the expected root directory the data generator outputs to
     * @param fileHelper the helper used to validate a texture's existence
     */
    public FFParticleDescriptionProvider(PackOutput output, ExistingFileHelper fileHelper) {
        super(output, fileHelper);
    }

    /**
     * Registers the particle descriptions generated by {@link #sprite(ParticleType, ResourceLocation)}
     * or one of the {@link #spriteSet(ParticleType, Iterable) sprite set methods}.
     *
     * <p>This particular particle could be registered more efficiently with the overload that takes
     * an integer, but I wanted to leave my options open.</p>
     */
    @Override protected void addDescriptions() {
        spriteSet(
                ParticleRegistry.MIST_PARTICLE.get(),
                ResourceLocation.withDefaultNamespace("generic_7"),
                ResourceLocation.withDefaultNamespace("generic_6"),
                ResourceLocation.withDefaultNamespace("generic_5"),
                ResourceLocation.withDefaultNamespace("generic_4"),
                ResourceLocation.withDefaultNamespace("generic_3"),
                ResourceLocation.withDefaultNamespace("generic_2"),
                ResourceLocation.withDefaultNamespace("generic_1"),
                ResourceLocation.withDefaultNamespace("generic_0")
        );
    }
}
